### ISSUE TITLE
Aborting Social login leads to error 500

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#170]
in this case the user should be redirected back to the login form

go to http://www.yawik.org/demo/en
Login via Facebook or Linkedin
now in the confirmation box for the App press abort
you will be redirected e.g. in case of facebook to http://yawik.org/demo/login/facebook?ref=%252Fen#_=_
with error message
<pre>
Ein Fehler ist aufgetreten
An error occurred during execution; please try again later.
Zusätzliche Informationen:
Zend\ServiceManager\Exception\ServiceNotCreatedException
Datei:
/data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:946
Nachricht:
An exception was raised while creating "HybridAuthAdapter"; no instance returned
Stapelverlauf:
#0 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauthadapt...', 'HybridAuthAdapt...')
#1 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauthadapt...', 'HybridAuthAdapt...')
#2 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('HybridAuthAdapt...', 'hybridauthadapt...')
#3 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#4 /data/www/clients/client1/web1/YAWIK/module/Auth/src/Auth/Controller/IndexController.php(180): Zend\ServiceManager\ServiceManager->get('HybridAuthAdapt...')
#5 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Auth\Controller\IndexController->loginAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /data/www/clients/client1/web1/YAWIK/public/index.php(55): Zend\Mvc\Application->run()
#16 {main}
Vorherige Exceptions:
Zend\ServiceManager\Exception\ServiceNotCreatedException
Datei:
/data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:946
Nachricht:
An exception was raised while creating "HybridAuth"; no instance returned
Stapelverlauf:
#0 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauth', 'HybridAuth')
#1 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauth', 'HybridAuth')
#2 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('HybridAuth', 'hybridauth')
#3 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#4 /data/www/clients/client1/web1/YAWIK/module/Auth/src/Auth/Factory/Adapter/HybridAuthAdapterFactory.php(35): Zend\ServiceManager\ServiceManager->get('HybridAuth')
#5 [internal function]: Auth\Factory\Adapter\HybridAuthAdapterFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'hybridauthadapt...', 'HybridAuthAdapt...')
#6 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'hybridauthadapt...', 'HybridAuthAdapt...')
#7 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauthadapt...', 'HybridAuthAdapt...')
#8 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauthadapt...', 'HybridAuthAdapt...')
#9 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('HybridAuthAdapt...', 'hybridauthadapt...')
#10 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#11 /data/www/clients/client1/web1/YAWIK/module/Auth/src/Auth/Controller/IndexController.php(180): Zend\ServiceManager\ServiceManager->get('HybridAuthAdapt...')
#12 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Auth\Controller\IndexController->loginAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /data/www/clients/client1/web1/YAWIK/public/index.php(55): Zend\Mvc\Application->run()
#23 {main}
Exception
Datei:
/data/www/clients/client1/web1/YAWIK/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php:169
Nachricht:
Authentication failed! The user denied your request.
Stapelverlauf:
#0 /data/www/clients/client1/web1/YAWIK/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php(55): Hybrid_Auth::initialize(Array)
#1 /data/www/clients/client1/web1/YAWIK/module/Auth/src/Auth/Factory/Service/HybridAuthFactory.php(61): Hybrid_Auth->__construct(Array)
#2 [internal function]: Auth\Factory\Service\HybridAuthFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'hybridauth', 'HybridAuth')
#3 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'hybridauth', 'HybridAuth')
#4 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauth', 'HybridAuth')
#5 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauth', 'HybridAuth')
#6 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('HybridAuth', 'hybridauth')
#7 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#8 /data/www/clients/client1/web1/YAWIK/module/Auth/src/Auth/Factory/Adapter/HybridAuthAdapterFactory.php(35): Zend\ServiceManager\ServiceManager->get('HybridAuth')
#9 [internal function]: Auth\Factory\Adapter\HybridAuthAdapterFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'hybridauthadapt...', 'HybridAuthAdapt...')
#10 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'hybridauthadapt...', 'HybridAuthAdapt...')
#11 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauthadapt...', 'HybridAuthAdapt...')
#12 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauthadapt...', 'HybridAuthAdapt...')
#13 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('HybridAuthAdapt...', 'hybridauthadapt...')
#14 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#15 /data/www/clients/client1/web1/YAWIK/module/Auth/src/Auth/Controller/IndexController.php(180): Zend\ServiceManager\ServiceManager->get('HybridAuthAdapt...')
#16 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Auth\Controller\IndexController->loginAction()
#17 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#22 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#23 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#24 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /data/www/clients/client1/web1/YAWIK/public/index.php(55): Zend\Mvc\Application->run()
#27 {main}
</pre>

**Comment by cbleek** [comment]
The Abort/Accept Callbacks should be set on the OAuth Server side.

Isn't this possible?
