### ISSUE TITLE
Removing an account leads to an error

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#469]
```
Fatal Error

Class YawikDemoSkin\Factory\Dependency\ManagerFactory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend\
ServiceManager\Factory\FactoryInterface::__invoke) search►

Source file

File: .../src/Factory/Dependency/ManagerFactory.php:27

17:    class ManagerFactory implements FactoryInterface
18:    {
19:
20:        public function createService(ServiceLocatorInterface $serviceLocator)
21:        {
22:            $manager = new \YawikDemoSkin\Dependency\Manager($serviceLocator->get('Core/DocumentManager'));
23:            $manager->setEventManager($serviceLocator->get('Auth/Dependency/Manager/Events'));
24:
25:            return $manager;
26:        }
27:    }
28:

```

**Comment by TiSiE** [comment]
This is a bug in the yawik/DemoSkin repository.

**Comment by cbleek** [comment]
Now the following Error occurse

### Zend\ServiceManager\Exception\ServiceNotCreatedException

```
Datei:
/var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:771
Nachricht:
Service with name "Auth\Controller\Remove" could not be created. Reason: Class 'Users\Entity\User' does not exist
Stapelverlauf:
#0 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Auth\\Controller...')
#1 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(141): Zend\ServiceManager\ServiceManager->get('Auth\\Controller...')
#2 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(102): Zend\ServiceManager\AbstractPluginManager->get('Auth\\Controller...')
#3 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#6 /var/www/yawik.org/public/index.php(56): Zend\Mvc\Application->run()
#7 {main}
```
### Vorherige Exceptions:

#### Doctrine\Common\Persistence\Mapping\MappingException

```
Datei:
/var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:96
Nachricht:
Class 'Users\Entity\User' does not exist
Stapelverlauf:
#0 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(41): Doctrine\Common\Persistence\Mapping\MappingException::nonExistingClass('Users\\Entity\\Us...')
#1 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(281): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getParentClasses('Users\\Entity\\Us...')
#2 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(311): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses('Users\\Entity\\Us...')
#3 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(216): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Users\\Entity\\Us...')
#4 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php(287): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Users\\Entity\\Us...')
#5 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Repository/AbstractRepositoryFactory.php(45): Doctrine\ODM\MongoDB\DocumentManager->getClassMetadata('\\Users\\Entity\\U...')
#6 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php(524): Doctrine\ODM\MongoDB\Repository\AbstractRepositoryFactory->getRepository(Object(Doctrine\ODM\MongoDB\DocumentManager), '\\Users\\Entity\\U...')
#7 /var/www/yawik.org/module/Core/src/Core/Repository/RepositoryService.php(41): Doctrine\ODM\MongoDB\DocumentManager->getRepository('\\Users\\Entity\\U...')
#8 /var/www/yawik.org/module/Auth/src/Auth/Factory/Controller/RemoveControllerFactory.php(30): Core\Repository\RepositoryService->get('Users')
#9 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(764): Auth\Factory\Controller\RemoveControllerFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Auth\\Controller...', NULL)
#10 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Auth\\Controller...')
#11 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(141): Zend\ServiceManager\ServiceManager->get('Auth\\Controller...')
#12 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(102): Zend\ServiceManager\AbstractPluginManager->get('Auth\\Controller...')
#13 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /var/www/yawik.org/public/index.php(56): Zend\Mvc\Application->run()
#17 {main}
```
