### ISSUE TITLE
Class 'InvoiceAddressSettings' does not exist

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#614]
the yawik/orders modul is loaded.https://github.com/cross-solution/YAWIK/blob/odm-module3/config/modules.php#L21

it has to be removed later in #613

```
Doctrine\Persistence\Mapping\MappingException
Datei:
/var/www/staging/releases/37/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php:94
Nachricht:
Class 'InvoiceAddressSettings' does not exist
Stapelverlauf:
#0 /var/www/staging/releases/37/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/RuntimeReflectionService.php(37): Doctrine\Persistence\Mapping\MappingException::nonExistingClass('InvoiceAddressS...')
#1 /var/www/staging/releases/37/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(251): Doctrine\Persistence\Mapping\RuntimeReflectionService->getParentClasses('InvoiceAddressS...')
#2 /var/www/staging/releases/37/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(284): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses('InvoiceAddressS...')
#3 /var/www/staging/releases/37/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(184): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('InvoiceAddressS...')
#4 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php(67): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('InvoiceAddressS...')
#5 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php(299): Doctrine\ODM\MongoDB\Mapping\ClassMetadataFactory->getMetadataFor('InvoiceAddressS...')
#6 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(2544): Doctrine\ODM\MongoDB\DocumentManager->getClassMetadata('InvoiceAddressS...')
#7 /var/www/staging/shared/var/cache/DoctrineMongoODMModule/Hydrator/OrdersEntitySettingsContainerHydrator.php(66): Doctrine\ODM\MongoDB\UnitOfWork->getClassNameForAssociation(Array, Array)
#8 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php(483): DoctrineMongoODMModule\Hydrator\OrdersEntitySettingsContainerHydrator->hydrate(Object(Orders\Entity\SettingsContainer), Array, Array)
#9 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(680): Doctrine\ODM\MongoDB\Hydrator\HydratorFactory->hydrate(Object(Orders\Entity\SettingsContainer), Array, Array)
#10 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php(638): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->loadEmbedManyCollection(Object(Doctrine\ODM\MongoDB\PersistentCollection))
#11 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(2648): Doctrine\ODM\MongoDB\Persisters\DocumentPersister->loadCollection(Object(Doctrine\ODM\MongoDB\PersistentCollection))
#12 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php(142): Doctrine\ODM\MongoDB\UnitOfWork->loadCollection(Object(Doctrine\ODM\MongoDB\PersistentCollection))
#13 /var/www/staging/releases/37/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php(490): Doctrine\ODM\MongoDB\PersistentCollection->initialize()
#14 /var/www/staging/releases/37/module/Auth/src/Auth/Entity/User.php(423): Doctrine\ODM\MongoDB\PersistentCollection->getIterator()
#15 /var/www/staging/releases/37/module/Core/src/I18n/Locale.php(47): Auth\Entity\User->getSettings('Core')
#16 /var/www/staging/releases/37/module/Auth/src/Auth/Controller/IndexController.php(155): Core\I18n\Locale->detectLanguage(Object(Laminas\Http\PhpEnvironment\Request), Object(Auth\Entity\User))
#17 /var/www/staging/releases/37/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Auth\Controller\IndexController->indexAction()
#18 /var/www/staging/releases/37/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#19 /var/www/staging/releases/37/vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#20 /var/www/staging/releases/37/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#21 /var/www/staging/releases/37/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#22 /var/www/staging/releases/37/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#23 /var/www/staging/releases/37/vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#24 /var/www/staging/releases/37/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#25 /var/www/staging/releases/37/public/index.php(30): Laminas\Mvc\Application->run()
#26 {main}
```

![Auswahl_999(791)](https://user-images.githubusercontent.com/858642/102820318-56e6e680-43d5-11eb-9b0d-dd12ac70fdc0.png)

**Comment by TiSiE** [comment]
This is the same issue as #611
